//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ab_artikelbezeichnung
    {
        public int ab_artikelbezeichnung_ID { get; set; }
        public string ab_artikelbezeichnung1 { get; set; }
        public System.DateTime ab_angelegt_am { get; set; }
        public string ab_angelegt_von { get; set; }
    }
}
