//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class at_anlagentarif
    {
        public int at_anlagentarif_ID { get; set; }
        public Nullable<int> at_anlagendatensatz_ID { get; set; }
        public string at_anlagennummer { get; set; }
        public string at_anlagengruppe { get; set; }
        public string at_anlagenbezeichnung { get; set; }
        public Nullable<float> at_tarif_anlage_pro_stunde { get; set; }
        public Nullable<float> at_tarif_personal_pro_stunde { get; set; }
        public Nullable<float> at_nennleistung_in_me { get; set; }
        public Nullable<int> at_losgroesse_in_me { get; set; }
        public Nullable<float> at_ruestdauer_in_std { get; set; }
        public Nullable<float> at_anlagenverfuegbarkeit { get; set; }
        public Nullable<float> at_betreuungsaufwand_produktiv { get; set; }
        public Nullable<float> at_betreuungsaufwand_ruesten { get; set; }
        public Nullable<int> at_schichten { get; set; }
        public string at_mengeneinheit { get; set; }
        public Nullable<float> at_ausschussquote { get; set; }
        public string at_angelegt_von { get; set; }
        public Nullable<System.DateTime> at_angelegt_am { get; set; }
    
        public virtual ds_at_anlagendatensatz ds_at_anlagendatensatz { get; set; }
    }
}
