//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class bh_bearbeitungshistorie
    {
        public int bh_ID { get; set; }
        public string bh_von { get; set; }
        public System.DateTime bh_am { get; set; }
        public string bh_sql { get; set; }
        public int bh_vorkalkulation_ID { get; set; }
    }
}
