//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_datei
    {
        public int d_datei_ID { get; set; }
        public string d_pfad { get; set; }
        public string d_name { get; set; }
        public string d_beschreibung { get; set; }
        public Nullable<int> d_vorkalkulation_ID { get; set; }
        public Nullable<int> d_kundenanfrage_ID { get; set; }
        public string d_status { get; set; }
        public string d_ungueltig_von { get; set; }
        public Nullable<System.DateTime> d_ungueltig_am { get; set; }
        public Nullable<System.DateTime> d_angelegt_am { get; set; }
        public string d_angelegt_von { get; set; }
    
        public virtual ka_kundenanfrage ka_kundenanfrage { get; set; }
    }
}
