//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class dp_drahtpreis
    {
        public int dp_drahtpreis_ID { get; set; }
        public Nullable<int> dp_nummer { get; set; }
        public string dp_gruppe { get; set; }
        public string dp_bezeichnung { get; set; }
        public string dp_lieferant { get; set; }
        public Nullable<float> dp_preis_pro_tonne { get; set; }
        public Nullable<float> dp_schrottfaktor { get; set; }
        public Nullable<float> dp_schrotterloes_pro_tonne { get; set; }
        public System.DateTime dp_angelegt_am { get; set; }
        public int dp_drahtpreisdatensatz_ID { get; set; }
        public string dp_angelegt_von { get; set; }
    
        public virtual ds_dp_drahtpreisdatensatz ds_dp_drahtpreisdatensatz { get; set; }
    }
}
