//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class dpos_drahtposition
    {
        public dpos_drahtposition()
        {
            this.vk_dpos = new HashSet<vk_dpos>();
        }
    
        public int dpos_drahtposition_ID { get; set; }
        public Nullable<int> dpos_nummer { get; set; }
        public string dpos_ungültig_von { get; set; }
        public string dpos_gruppe { get; set; }
        public string dpos_bezeichnung { get; set; }
        public string dpos_lieferant { get; set; }
        public Nullable<float> dpos_preis_pro_tonne { get; set; }
        public Nullable<float> dpos_schrottfaktor { get; set; }
        public Nullable<float> dpos_schrotterloes_pro_tonne { get; set; }
        public Nullable<float> dpos_kosten { get; set; }
        public string dpos_status { get; set; }
        public Nullable<System.DateTime> dpos_angelegt_am { get; set; }
        public Nullable<float> dpos_mgk_faktor { get; set; }
        public Nullable<float> dpos_einsatzgewicht_in_tonnen { get; set; }
        public Nullable<float> dpos_schrottgewicht_einsatzgewicht_in_tonnen { get; set; }
        public Nullable<System.DateTime> dpos_gültigkeit { get; set; }
        public Nullable<float> dpos_schrottgewicht_diff_in_tonnen { get; set; }
        public string dpos_angelegt_von { get; set; }
        public Nullable<int> dpos_ds_ID { get; set; }
    
        public virtual ICollection<vk_dpos> vk_dpos { get; set; }
    }
}
