//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_at_anlagendatensatz
    {
        public ds_at_anlagendatensatz()
        {
            this.at_anlagentarif = new HashSet<at_anlagentarif>();
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_at_anlagendatensatz_ID { get; set; }
        public System.DateTime ds_at_angelegt_am { get; set; }
        public string ds_at_angelegt_von { get; set; }
    
        public virtual ICollection<at_anlagentarif> at_anlagentarif { get; set; }
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
