//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_dp_drahtpreisdatensatz
    {
        public ds_dp_drahtpreisdatensatz()
        {
            this.dp_drahtpreis = new HashSet<dp_drahtpreis>();
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_dp_drahtpreisdatensatz_ID { get; set; }
        public System.DateTime ds_dp_angelegt_am { get; set; }
        public string ds_dp_angelegt_von { get; set; }
    
        public virtual ICollection<dp_drahtpreis> dp_drahtpreis { get; set; }
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
