//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_ext_teildatensatz
    {
        public ds_ext_teildatensatz()
        {
            this.ext_teilpreis = new HashSet<ext_teilpreis>();
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_ext_teildatensatz_ID { get; set; }
        public string ds_ext_angelegt_von { get; set; }
        public System.DateTime ds_ext_angelegt_am { get; set; }
    
        public virtual ICollection<ext_teilpreis> ext_teilpreis { get; set; }
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
