//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_exd_dienstleistungsdatensatz
    {
        public ds_exd_dienstleistungsdatensatz()
        {
            this.exd_dienstleistungspreis = new HashSet<exd_dienstleistungspreis>();
        }
    
        public int ds_exd_dienstleistungsdatensatz_ID { get; set; }
        public System.DateTime ds_exd_angelegt_am { get; set; }
        public string ds_exd_angelegt_von { get; set; }
    
        public virtual ICollection<exd_dienstleistungspreis> exd_dienstleistungspreis { get; set; }
    }
}
