//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_gk_gemeinkostendatensatz
    {
        public ds_gk_gemeinkostendatensatz()
        {
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_gk_gemeinkostendatensatz_ID { get; set; }
        public Nullable<float> ds_gk_mgk1 { get; set; }
        public Nullable<float> ds_gk_mgk2 { get; set; }
        public Nullable<float> ds_gk_mgk3 { get; set; }
        public Nullable<float> ds_gk_fgk { get; set; }
        public Nullable<float> ds_gk_vwgk { get; set; }
        public Nullable<System.DateTime> ds_gk_angelegt_am { get; set; }
        public string ds_gk_angelegt_von { get; set; }
    
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
