//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_sk_sonderkostendatensatz
    {
        public ds_sk_sonderkostendatensatz()
        {
            this.sk_sonderkostenpreis = new HashSet<sk_sonderkostenpreis>();
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_sk_sonderkostendatensatz_ID { get; set; }
        public System.DateTime ds_sk_angelegt_am { get; set; }
        public string ds_sk_angelegt_von { get; set; }
    
        public virtual ICollection<sk_sonderkostenpreis> sk_sonderkostenpreis { get; set; }
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
