//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_wz_werkzeugdatensatz
    {
        public ds_wz_werkzeugdatensatz()
        {
            this.wz_werkzeugpreis = new HashSet<wz_werkzeugpreis>();
            this.vk_vorkalkulation = new HashSet<vk_vorkalkulation>();
        }
    
        public int ds_wz_werkzeugdatensatz_ID { get; set; }
        public System.DateTime ds_wz_angelegt_am { get; set; }
        public string ds_wz_angelegt_von { get; set; }
    
        public virtual ICollection<wz_werkzeugpreis> wz_werkzeugpreis { get; set; }
        public virtual ICollection<vk_vorkalkulation> vk_vorkalkulation { get; set; }
    }
}
