//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class exdpos_dienstleistungsposition
    {
        public exdpos_dienstleistungsposition()
        {
            this.vk_exdpos = new HashSet<vk_exdpos>();
        }
    
        public int exdpos_dienstleistungsposition_ID { get; set; }
        public Nullable<int> exdpos_nummer { get; set; }
        public Nullable<System.DateTime> exdpos_angelegt_am { get; set; }
        public string exdpos_angelegt_von { get; set; }
        public string exdpos_gruppe { get; set; }
        public string exdpos_bezeichnung { get; set; }
        public string exdpos_abmessung { get; set; }
        public string exdpos_lieferant { get; set; }
        public Nullable<float> exdpos_preis_pro_me { get; set; }
        public Nullable<float> exdpos_kosten { get; set; }
        public Nullable<float> exdpos_leistungsfaktor { get; set; }
        public string exdpos_mengeneinheit { get; set; }
        public Nullable<float> exdpos_mgk2_faktor { get; set; }
        public Nullable<int> exdpos_setze_gk_0 { get; set; }
        public Nullable<int> exdpos_ds_ID { get; set; }
    
        public virtual ICollection<vk_exdpos> vk_exdpos { get; set; }
        public virtual me_mengeneinheit me_mengeneinheit { get; set; }
    }
}
