//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext_teilpreis
    {
        public int ext_teilpreis_ID { get; set; }
        public Nullable<int> ext_teildatensatz_ID { get; set; }
        public Nullable<int> ext_nummer { get; set; }
        public string ext_gruppe { get; set; }
        public string ext_bezeichnung { get; set; }
        public string ext_abmessung { get; set; }
        public string ext_lieferant { get; set; }
        public string ext_mengeneinheit { get; set; }
        public Nullable<float> ext_preis_pro_me { get; set; }
        public Nullable<float> ext_leistungsfaktor { get; set; }
        public string ext_angelegt_von { get; set; }
        public System.DateTime ext_angelegt_am { get; set; }
        public string ext_teilpreiscol { get; set; }
    
        public virtual ds_ext_teildatensatz ds_ext_teildatensatz { get; set; }
        public virtual me_mengeneinheit me_mengeneinheit { get; set; }
    }
}
