//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class f_freigabe
    {
        public int f_freigabe_ID { get; set; }
        public int f_vorkalkulation_ID { get; set; }
        public string f_kommentar { get; set; }
        public string f_status { get; set; }
        public Nullable<System.DateTime> f_ungueltig_am { get; set; }
        public string f_angelegt_von { get; set; }
        public System.DateTime f_angelegt_am { get; set; }
        public string f_ungueltig_von { get; set; }
    
        public virtual vk_vorkalkulation vk_vorkalkulation { get; set; }
    }
}
