//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_kunde
    {
        public k_kunde()
        {
            this.e_einkaeufer = new SortableBindingList<e_einkaeufer>();
        }
    
        public int k_kunde_ID { get; set; }
        public string k_kunde1 { get; set; }
        public System.DateTime k_angelegt_am { get; set; }
        public string k_angelegt_von { get; set; }
        public string k_status { get; set; }
        public string k_kundengruppe { get; set; }
        public string k_vertreter { get; set; }
        public System.DateTime k_ungueltig_am { get; set; }
        public string k_ungueltig_von { get; set; }
        public string k_kommentar { get; set; }

        public virtual SortableBindingList<e_einkaeufer> e_einkaeufer { get; set; }
    }
}
