//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunde_einkaeufer_join
    {
        public int ka_kundenanfrage_ID { get; set; }
        public Nullable<int> ka_anfragenummer { get; set; }
        public string ka_artikelnummer { get; set; }
        public string ka_verwendung { get; set; }
        public string ka_kommentar { get; set; }
        public Nullable<System.DateTime> ka_angefragt_am { get; set; }
        public Nullable<System.DateTime> ka_angebotsfrist { get; set; }
        public string ka_hersteller { get; set; }
        public string ka_zustaendig { get; set; }
        public System.DateTime ka_angelegt_am { get; set; }
        public string ka_angelegt_von { get; set; }
        public string ka_status { get; set; }
        public Nullable<System.DateTime> ka_ungueltig_am { get; set; }
        public string ka_ungueltig_von { get; set; }
        public string ka_modus { get; set; }
        public string ka_kunde { get; set; }
        public string ka_produktgruppe { get; set; }
        public string ka_artikelbezeichnung { get; set; }
        public string ka_guete { get; set; }
        public string ka_zeichnungsnummer { get; set; }
        public string ka_aenderungsindex { get; set; }
        public Nullable<float> ka_durchmesser { get; set; }
        public Nullable<float> ka_laenge { get; set; }
        public Nullable<float> ka_gewindesteigung { get; set; }
        public Nullable<float> ka_fertiggewicht { get; set; }
        public Nullable<float> ka_einsatzgewicht { get; set; }
        public string ka_abc_artikelnummer { get; set; }
        public string ka_einkaeufer_name { get; set; }
        public string ka_einkaeufer_email { get; set; }
        public string ka_einkaeufer_telefon { get; set; }
        public string ka_einkaeufer_fax { get; set; }
        public string ka_einkaeufer_mobil { get; set; }
        public string ka_einkaeufer_anrede { get; set; }
        public string ka_kundengruppe { get; set; }
        public string ka_vertreter { get; set; }
        public string ka_kundenkommentar { get; set; }
        public Nullable<int> ka_einkaeufer_ID { get; set; }
        public Nullable<int> ka_offen_vertrieb { get; set; }
        public Nullable<int> ka_offen_te { get; set; }
        public Nullable<int> ka_vk_angefordert { get; set; }
        public string ka_vk_kommentar { get; set; }
        public int k_kunde_ID { get; set; }
        public string k_kunde { get; set; }
        public System.DateTime k_angelegt_am { get; set; }
        public string k_angelegt_von { get; set; }
        public string k_status { get; set; }
        public string k_kundengruppe { get; set; }
        public string k_vertreter { get; set; }
        public System.DateTime k_ungueltig_am { get; set; }
        public string k_ungueltig_von { get; set; }
        public string k_kommentar { get; set; }
        public int e_einkaeufer_ID { get; set; }
        public int e_kunde_ID { get; set; }
        public string e_anrede { get; set; }
        public string e_einkaeufer { get; set; }
        public string e_email { get; set; }
        public string e_telefon { get; set; }
        public string e_mobil { get; set; }
        public string e_fax { get; set; }
        public string e_kommentar { get; set; }
        public System.DateTime e_angelegt_am { get; set; }
        public string e_angelegt_von { get; set; }
        public string e_status { get; set; }
        public Nullable<System.DateTime> e_ungueltig_am { get; set; }
        public string e_ungueltig_von { get; set; }
    }
}
