//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class me_mengeneinheit
    {
        public me_mengeneinheit()
        {
            this.apos_anlagenposition = new HashSet<apos_anlagenposition>();
            this.exd_dienstleistungspreis = new HashSet<exd_dienstleistungspreis>();
            this.exdpos_dienstleistungsposition = new HashSet<exdpos_dienstleistungsposition>();
            this.ext_teilpreis = new HashSet<ext_teilpreis>();
            this.extpos_teilposition = new HashSet<extpos_teilposition>();
        }
    
        public string me_mengeneinheit1 { get; set; }
        public Nullable<float> me_faktor { get; set; }
        public string me_leistungsbezeichnung { get; set; }
        public string me_losgroesseneinheit { get; set; }
        public string me_nummer { get; set; }
    
        public virtual ICollection<apos_anlagenposition> apos_anlagenposition { get; set; }
        public virtual ICollection<exd_dienstleistungspreis> exd_dienstleistungspreis { get; set; }
        public virtual ICollection<exdpos_dienstleistungsposition> exdpos_dienstleistungsposition { get; set; }
        public virtual ICollection<ext_teilpreis> ext_teilpreis { get; set; }
        public virtual ICollection<extpos_teilposition> extpos_teilposition { get; set; }
    }
}
