//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class angebotserstellungEntities : DbContext
    {
        public angebotserstellungEntities()
            : base("name=angebotserstellungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ab_artikelbezeichnung> ab_artikelbezeichnung { get; set; }
        public DbSet<apos_anlagenposition> apos_anlagenposition { get; set; }
        public DbSet<as_abteilungsstatus> as_abteilungsstatus { get; set; }
        public DbSet<at_anlagentarif> at_anlagentarif { get; set; }
        public DbSet<bh_bearbeitungshistorie> bh_bearbeitungshistorie { get; set; }
        public DbSet<d_datei> d_datei { get; set; }
        public DbSet<dp_drahtpreis> dp_drahtpreis { get; set; }
        public DbSet<dpos_drahtposition> dpos_drahtposition { get; set; }
        public DbSet<ds_at_anlagendatensatz> ds_at_anlagendatensatz { get; set; }
        public DbSet<ds_dp_drahtpreisdatensatz> ds_dp_drahtpreisdatensatz { get; set; }
        public DbSet<ds_exd_dienstleistungsdatensatz> ds_exd_dienstleistungsdatensatz { get; set; }
        public DbSet<ds_ext_teildatensatz> ds_ext_teildatensatz { get; set; }
        public DbSet<ds_gk_gemeinkostendatensatz> ds_gk_gemeinkostendatensatz { get; set; }
        public DbSet<ds_sk_sonderkostendatensatz> ds_sk_sonderkostendatensatz { get; set; }
        public DbSet<ds_wz_werkzeugdatensatz> ds_wz_werkzeugdatensatz { get; set; }
        public DbSet<e_einkaeufer> e_einkaeufer { get; set; }
        public DbSet<exd_dienstleistungspreis> exd_dienstleistungspreis { get; set; }
        public DbSet<exdpos_dienstleistungsposition> exdpos_dienstleistungsposition { get; set; }
        public DbSet<ext_teilpreis> ext_teilpreis { get; set; }
        public DbSet<extpos_teilposition> extpos_teilposition { get; set; }
        public DbSet<f_freigabe> f_freigabe { get; set; }
        public DbSet<fb_freigabeberechtigung> fb_freigabeberechtigung { get; set; }
        public DbSet<g_guete> g_guete { get; set; }
        public DbSet<h_hersteller> h_hersteller { get; set; }
        public DbSet<k_kunde> k_kunde { get; set; }
        public DbSet<ka_kundenanfrage> ka_kundenanfrage { get; set; }
        public DbSet<kg_kundengruppe> kg_kundengruppe { get; set; }
        public DbSet<m_mengenpos> m_mengenpos { get; set; }
        public DbSet<me_mengeneinheit> me_mengeneinheit { get; set; }
        public DbSet<mv_mitarbeiter_vertrieb> mv_mitarbeiter_vertrieb { get; set; }
        public DbSet<pg_produktgruppe> pg_produktgruppe { get; set; }
        public DbSet<s_vertriebsstatus> s_vertriebsstatus { get; set; }
        public DbSet<sk_sonderkostenpreis> sk_sonderkostenpreis { get; set; }
        public DbSet<skpos_sonderkostenposition> skpos_sonderkostenposition { get; set; }
        public DbSet<v_vertreter> v_vertreter { get; set; }
        public DbSet<vk_apos> vk_apos { get; set; }
        public DbSet<vk_dpos> vk_dpos { get; set; }
        public DbSet<vk_exdpos> vk_exdpos { get; set; }
        public DbSet<vk_extpos> vk_extpos { get; set; }
        public DbSet<vk_skpos> vk_skpos { get; set; }
        public DbSet<vk_vorkalkulation> vk_vorkalkulation { get; set; }
        public DbSet<vk_wzpos> vk_wzpos { get; set; }
        public DbSet<wz_werkzeugpreis> wz_werkzeugpreis { get; set; }
        public DbSet<wzpos_werkzeugposition> wzpos_werkzeugposition { get; set; }
        public DbSet<dt_vk_vertrieb_join> dt_vk_vertrieb_join { get; set; }
        public DbSet<ka_kundenanfrage_join> ka_kundenanfrage_join { get; set; }
        public DbSet<ka_kundenanfrage_mengenpos_join> ka_kundenanfrage_mengenpos_join { get; set; }
        public DbSet<kunde_einkaeufer_join> kunde_einkaeufer_join { get; set; }
        public DbSet<vk_apos_join> vk_apos_join { get; set; }
        public DbSet<vk_dpos_join> vk_dpos_join { get; set; }
        public DbSet<vk_exdpos_join> vk_exdpos_join { get; set; }
        public DbSet<vk_extpos_join> vk_extpos_join { get; set; }
        public DbSet<vk_skpos_join> vk_skpos_join { get; set; }
        public DbSet<vk_vertrieb_join> vk_vertrieb_join { get; set; }
        public DbSet<vk_wzpos_join> vk_wzpos_join { get; set; }
        public DbSet<vk_te_mitarbeiter> vk_te_mitarbeiter { get; set; }
    }
}
