//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class mv_mitarbeiter_vertrieb
    {
        public int mv_mitarbeiter_ID { get; set; }
        public string mv_email { get; set; }
        public string mv_name { get; set; }
    }
}
