//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class sk_sonderkostenpreis
    {
        public int sk_sonderkostenpreis_ID { get; set; }
        public int sk_sonderkostendatensatz_ID { get; set; }
        public Nullable<int> sk_nummer { get; set; }
        public string sk_gruppe { get; set; }
        public string sk_bezeichnung { get; set; }
        public Nullable<float> sk_preis { get; set; }
        public System.DateTime sk_angelegt_am { get; set; }
        public string sk_angelegt_von { get; set; }
    
        public virtual ds_sk_sonderkostendatensatz ds_sk_sonderkostendatensatz { get; set; }
    }
}
