//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class skpos_sonderkostenposition
    {
        public skpos_sonderkostenposition()
        {
            this.vk_skpos = new HashSet<vk_skpos>();
        }
    
        public int skpos_sonderkostenposition_ID { get; set; }
        public Nullable<int> skpos_nummer { get; set; }
        public string skpos_gruppe { get; set; }
        public string skpos_bezeichnung { get; set; }
        public Nullable<float> skpos_preis { get; set; }
        public Nullable<float> skpos_kosten { get; set; }
        public Nullable<int> skpos_ds_ID { get; set; }
        public Nullable<System.DateTime> skpos_angelegt_am { get; set; }
        public string skpos_angelegt_von { get; set; }
    
        public virtual ICollection<vk_skpos> vk_skpos { get; set; }
    }
}
