//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_apos_join
    {
        public int vk_apos_ID { get; set; }
        public Nullable<int> vk_apos_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_apos_anlagenposition_ID { get; set; }
        public int apos_anlagenposition_ID { get; set; }
        public string apos_anlagennummer { get; set; }
        public Nullable<int> apos_avonr { get; set; }
        public string apos_anlagengruppe { get; set; }
        public string apos_anlagenbezeichnung { get; set; }
        public Nullable<float> apos_tarif_anlage_pro_std { get; set; }
        public Nullable<float> apos_tarif_personal_pro_std { get; set; }
        public Nullable<float> apos_nennleistung_in_me { get; set; }
        public Nullable<int> apos_losgroesse_in_me { get; set; }
        public Nullable<float> apos_ruestdauer_in_std { get; set; }
        public Nullable<float> apos_anlagenverfuegbarkeit { get; set; }
        public Nullable<float> apos_betreuungsaufwand_produktiv { get; set; }
        public Nullable<float> apos_betreuungsaufwand_ruesten { get; set; }
        public Nullable<int> apos_schichten { get; set; }
        public Nullable<float> apos_ausschussquote { get; set; }
        public Nullable<System.DateTime> apos_angelegt_am { get; set; }
        public string apos_angelegt_von { get; set; }
        public string apos_status { get; set; }
        public string apos_ungültig_von { get; set; }
        public Nullable<float> apos_ruestkosten { get; set; }
        public Nullable<float> apos_produktionskosten_pro_me { get; set; }
        public Nullable<float> apos_ruestkosten_pro_st_kg { get; set; }
        public Nullable<float> apos_ruestkosten_pro_los { get; set; }
        public Nullable<float> apos_produktionskosten { get; set; }
        public Nullable<float> apos_maschinenkosten_pro_me { get; set; }
        public Nullable<float> apos_personalkosten_pro_me { get; set; }
        public Nullable<float> apos_fgk_faktor { get; set; }
        public string apos_mengeneinheit { get; set; }
        public Nullable<float> apos_menge_in_me { get; set; }
        public Nullable<int> apos_ds_ID { get; set; }
    }
}
