//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_dpos
    {
        public int vk_dpos_ID { get; set; }
        public int vk_dpos_vorkalkulation_ID { get; set; }
        public int vk_dpos_drahtposition_ID { get; set; }
    
        public virtual dpos_drahtposition dpos_drahtposition { get; set; }
    }
}
