//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_exdpos
    {
        public int vk_exdpos_ID { get; set; }
        public Nullable<int> vk_exdpos_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_exdpos_dienstleistungsposition_ID { get; set; }
    
        public virtual exdpos_dienstleistungsposition exdpos_dienstleistungsposition { get; set; }
    }
}
