//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_skpos_join
    {
        public int vk_skpos_ID { get; set; }
        public Nullable<int> vk_skpos_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_skpos_sonderkostenposition_ID { get; set; }
        public int skpos_sonderkostenposition_ID { get; set; }
        public Nullable<int> skpos_nummer { get; set; }
        public string skpos_gruppe { get; set; }
        public string skpos_bezeichnung { get; set; }
        public Nullable<float> skpos_preis { get; set; }
        public Nullable<float> skpos_kosten { get; set; }
        public Nullable<int> skpos_ds_ID { get; set; }
        public Nullable<System.DateTime> skpos_angelegt_am { get; set; }
        public string skpos_angelegt_von { get; set; }
    }
}
