//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_skpos
    {
        public int vk_skpos_ID { get; set; }
        public Nullable<int> vk_skpos_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_skpos_sonderkostenposition_ID { get; set; }
    
        public virtual skpos_sonderkostenposition skpos_sonderkostenposition { get; set; }
    }
}
