//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_vorkalkulation
    {
        public vk_vorkalkulation()
        {
            this.f_freigabe = new HashSet<f_freigabe>();
        }
    
        public int vk_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_mengenPos_ID { get; set; }
        public System.DateTime vk_angelegt_am { get; set; }
        public string vk_angelegt_von { get; set; }
        public Nullable<System.DateTime> vk_bearbeitet_am { get; set; }
        public string vk_bearbeitet_von { get; set; }
        public Nullable<System.DateTime> vk_abgelehnt_am { get; set; }
        public string vk_abgelehnt_von { get; set; }
        public string vk_status { get; set; }
        public string vk_ungültig_am { get; set; }
        public string vk_ungültig_von { get; set; }
        public string vk_kommentar_vertrieb { get; set; }
        public string vk_kommentar_te { get; set; }
        public Nullable<int> vk_gueltigkeit_tage { get; set; }
        public Nullable<System.DateTime> vk_gueltigkeit_datum { get; set; }
        public Nullable<int> vk_ta_te_anfrage_ID { get; set; }
        public Nullable<int> vk_anlagendatensatz_ID { get; set; }
        public Nullable<float> vk_lieferzeit_in_wochen { get; set; }
        public Nullable<float> vk_rohstoffkosten { get; set; }
        public Nullable<float> vk_dienstleistungskosten { get; set; }
        public Nullable<float> vk_werkzeugkosten { get; set; }
        public Nullable<float> vk_teilkosten { get; set; }
        public Nullable<float> vk_materialkosten { get; set; }
        public Nullable<float> vk_produktionskosten { get; set; }
        public Nullable<float> vk_ruestkosten { get; set; }
        public Nullable<float> vk_fertigungskosten { get; set; }
        public Nullable<float> vk_grenzherstellkosten { get; set; }
        public Nullable<float> vk_herstellkosten { get; set; }
        public Nullable<float> vk_verwaltungsgemeinkosten { get; set; }
        public Nullable<float> vk_selbstkosten { get; set; }
        public Nullable<float> vk_sonderkosten { get; set; }
        public Nullable<int> vk_drahtpreisdatensatz_ID { get; set; }
        public Nullable<int> vk_gemeinkostendatensatz_ID { get; set; }
        public Nullable<int> vk_dienstleistungsdatensatz_ID { get; set; }
        public Nullable<int> vk_werkzeugdatensatz_ID { get; set; }
        public Nullable<int> vk_teildatensatz_ID { get; set; }
        public Nullable<int> vk_sonderkostendatensatz_ID { get; set; }
        public bool vk_dspr1 { get; set; }
        public bool vk_dspr2 { get; set; }
        public bool vk_dspr3 { get; set; }
        public bool vk_dspr4 { get; set; }
        public bool vk_dspr5 { get; set; }
        public bool vk_dspr6 { get; set; }
        public bool vk_dspr7 { get; set; }
        public bool vk_dspr8 { get; set; }
        public Nullable<int> vk_geschlossen { get; set; }
        public Nullable<int> vk_abgelehnt { get; set; }
        public Nullable<int> vk_gf_freigabe { get; set; }
        public Nullable<int> vk_freigegeben { get; set; }
        public Nullable<int> vk_veroeffentlicht { get; set; }
    
        public virtual ds_at_anlagendatensatz ds_at_anlagendatensatz { get; set; }
        public virtual ds_dp_drahtpreisdatensatz ds_dp_drahtpreisdatensatz { get; set; }
        public virtual ds_ext_teildatensatz ds_ext_teildatensatz { get; set; }
        public virtual ds_gk_gemeinkostendatensatz ds_gk_gemeinkostendatensatz { get; set; }
        public virtual ds_sk_sonderkostendatensatz ds_sk_sonderkostendatensatz { get; set; }
        public virtual ds_wz_werkzeugdatensatz ds_wz_werkzeugdatensatz { get; set; }
        public virtual ICollection<f_freigabe> f_freigabe { get; set; }
        public virtual m_mengenpos m_mengenpos { get; set; }
    }
}
