//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class vk_wzpos
    {
        public int vk_wzpos_ID { get; set; }
        public Nullable<int> vk_wzpos_vorkalkulation_ID { get; set; }
        public Nullable<int> vk_wzpos_werkzeugposition_ID { get; set; }
    
        public virtual wzpos_werkzeugposition wzpos_werkzeugposition { get; set; }
    }
}
