//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MysqlApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class wz_werkzeugpreis
    {
        public int wz_werkzeugpreis_ID { get; set; }
        public int wz_werkzeugdatensatz_ID { get; set; }
        public Nullable<int> wz_nummer { get; set; }
        public string wz_gruppe { get; set; }
        public string wz_bezeichnung { get; set; }
        public Nullable<float> wz_standzeit { get; set; }
        public Nullable<float> wz_preis { get; set; }
        public System.DateTime wz_angelegt_am { get; set; }
        public string wz_angelegt_von { get; set; }
    
        public virtual ds_wz_werkzeugdatensatz ds_wz_werkzeugdatensatz { get; set; }
    }
}
